= Ideas

This file is a lightweight parking lot for ideas that are not yet ready to become OpenSpec changes.
Use it for questions, possible future directions, design sketches, and product thoughts that need more exploration.

When an idea becomes concrete enough to describe as a bounded change, promote it into `openspec/changes/<change-name>/` with a proposal, design, specs, and tasks.
Until then, ideas here are notes only and do not represent current system behavior or committed future work.

== Candidate ideas

* /opsx-propose: sometimes values are different only because of a timestamp.  Rather than completely ignoring the column for comparison, we could instead handle it by scrubbing the values, similar to approval/character tests.  To support this, let's add an SPI, ColumnValueNormalizer , and then have an implementation that looks for an extended property, 'cfct.normalizeMask'.  The value of this should be the mask to match for, and if it is a match then the value should be scrubbed to the mask.  For example, if the value is '2026-04-20T14:08:09.050 - VT - [RENT, RENT_FIXED] - 2026-06-01 - 2026-06-01/2026-07-01' and the mask is 'yyyy-MM-ddThh:MM.ss.SSS', then this value should be normalized to 'yyyy-MM-ddThh:MM.ss.SSS - VT - [RENT, RENT_FIXED] - 2026-06-01 - 2026-06-01/2026-07-01'.  Because this is most easily implemented using java functionality, this normalization should _NOT_ be performed in the SQL, instead the SQL will return non-matching values but the client-side Java code can then be applied (meaning the rows might end up being matching and therefore suppressed in the UI).

=== Cosmetic

* /opsx-propose: extend the build to pick up the git commit; incorporate onto the status bar as a version number.

* /opsx-propose: when initially select on a command, the corresponding selected business tables aren't (always? sometimes?) shown ... I have to uncheck and re-check the 'Selected only' checkbox

=== New features

* /opsx-propose: extend the library so that it can perform comparisons multi-threaded, each table in its own thread, rather than one at a time. To support this, there will (I imagine) need to be a connection pool / DataSource. The size of this pool should be specified as a cli argument, or read from a config property

* /opsx-propose: use spring native to compile the cli into an exe. Put this behind a profile, only built on demand (I believe it can take some time to run). Update README to explain how to build, using this profile. Update README to explain how to run (instead of using that shell script).
+
I attempted this, but failed to build.
See `native-image-failed` branch.


=== Programming Style

* /opsx-propose: followed preferred programming style: use @ConfigurationProperties for all config properties, so that these are typesafe.

* /opsx-propose: followed preferred programming style: don't hardcode package names, as we see in '@SpringBootApplication(scanBasePackages = "com.danhaywood.cfct.cli")'. Instead, use an appropriate class (create one if necessary) and use the .class literal.

* /opsx-propose: followed preferred programming style: clean up HomePageConnectionStatusPlaywrightSuccessTest, externalize DDL into a resources file. Do this elsewhere if necessary.

* /opsx-propose: followed preferred programming style: convert PlaywrightSqlServerFixture to be a regular service/bean, don't use static methods

* /opsx-propose: refactor the playwright tests to use page objects. Put the page objects into their own maven module, update maven module dependencies accordingly.

* /opsx-propose: followed preferred programming style: use lombok @Getter, @Setter and @RequiredArgsConstructor to remove boilerplate. Don't use other lombok conventions, though.

* /opsx-propose: Vaadin best practices.
