spring:
  datasource:
    url: jdbc:sqlserver://localhost:14333;encrypt=false;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Str0ng_password!123

cfct:
  webapp:
    comparison:
      left-database: left_db
      right-database: right_db
      env-file: .env
      output:
        format: text
        file:
      validation:
        enabled: true
        fail-fast: true
    selection-plan:
      explicit:
        tables:
          - dbo.Supplier
