spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=estatio;encrypt=false;trustServerCertificate=true
spring.datasource.username=estatio
spring.datasource.password=pass

isis.persistence.schema.create-schema-sql-template=IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = '%1$s') BEGIN EXEC ('CREATE SCHEMA %1$s'); END

server.port=10010

cfct.webapp.connection.left-database=estatio
cfct.webapp.connection.right-database=estatio_alt

server.servlet.session.cookie.name=JSESSION_CFCT
